{
 "title": "OAI-UI",
 "description": "OAI统计数据展示界面",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   {
    "name": "srcIP",
    "label": "源IP",
    "query": "SELECT DISTINCT INET_NTOA(srcIP) FROM `measure`"
   },
   {
    "name": "srcPort",
    "label": "源端口",
    "query": "SELECT DISTINCT srcPort FROM `measure`"
   },
   {
    "name": "dstIP",
    "label": "目的IP",
    "query": "SELECT DISTINCT INET_NTOA(dstIP) FROM `measure`"
   },
   {
    "name": "dstPort",
    "label": "目的端口",
    "query": "SELECT DISTINCT dstPort FROM `measure`"
   },
   {
    "name": "protocol",
    "label": "协议号",
    "query": "SELECT DISTINCT protocol FROM `measure`"
   },
   {
    "name": "flow",
    "label": "业务流",
    "query": "SELECT CONCAT(INET_NTOA(srcIP),' : ',srcPort,'->',INET_NTOA(dstIP),' : ',dstPort,' 协议号 ',protocol) \nFROM `measure` \nWHERE\n(INET_NTOA(srcIP) = '$srcIP' OR '$srcIP' = 'NULL') AND\n(INET_NTOA(dstIP) = '$dstIP' OR '$dstIP' = 'NULL') AND\n(srcPort = $srcPort OR '$srcPort' = 'NULL') AND\n(dstPort = $dstPort OR '$dstPort' = 'NULL') AND\n(protocol = $protocol OR '$protocol' = 'NULL') "
   }
  ]
 },
 "panels": [
  {
   "title": "上行流量统计",
   "type": "timeseries",
   "description": "此界面展示了当前eNB上行流量的统计信息，包括总的包数和比特数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(data_time_date,1s),\n  avg(totalBytes) AS \"totalBytes\"\nFROM total_send\nWHERE\n  $__timeFilter(data_time_date)\nGROUP BY 1\nORDER BY $__timeGroup(data_time_date,1s)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(data_time_date,1s),\n  avg(totalPkts) AS \"totalPkts\"\nFROM total_send\nWHERE\n  $__timeFilter(data_time_date)\nGROUP BY 1\nORDER BY $__timeGroup(data_time_date,1s)"
    }
   ]
  },
  {
   "title": "下行流量统计",
   "type": "timeseries",
   "description": "此界面展示了当前eNB下行流量的统计信息，包括总的包数和比特数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(data_time_date,1s),\n  avg(totalBytes) AS \"totalBytes\"\nFROM total_recv\nWHERE\n  $__timeFilter(data_time_date)\nGROUP BY 1\nORDER BY $__timeGroup(data_time_date,1s)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(data_time_date,1s),\n  avg(totalPkts) AS \"totalPkts\"\nFROM total_recv\nWHERE\n  $__timeFilter(data_time_date)\nGROUP BY 1\nORDER BY $__timeGroup(data_time_date,1s)"
    }
   ]
  },
  {
   "title": "时延信息",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(data_time_date,1s),\n  CONCAT(INET_NTOA(srcIP),' : ',srcPort,'->',INET_NTOA(dstIP),' : ',dstPort) AS metric,\n  avg(delay)\nFROM delayloss\nWHERE\n  $__timeFilter(data_time_date) AND\n  (INET_NTOA(srcIP) = '$srcIP' OR '$srcIP' = 'NULL') AND\n  (INET_NTOA(dstIP) = '$dstIP' OR '$dstIP' = 'NULL') AND\n  (srcPort = '$srcPort' OR '$srcPort' = 'NULL') AND\n  (dstPort = '$dstPort' OR '$dstPort' = 'NULL') AND\n  (protocol = '$protocol' OR '$protocol' = 'NULL')\nGROUP BY 1,2\nORDER BY $__timeGroup(data_time_date,1s)"
    }
   ]
  },
  {
   "title": "丢包率信息",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(data_time_date,1s),\n  CONCAT(INET_NTOA(srcIP),' : ',srcPort,'->',INET_NTOA(dstIP),' : ',dstPort) AS metric,\n  avg(loss)\nFROM delayloss\nWHERE\n  $__timeFilter(data_time_date) AND\n  (INET_NTOA(srcIP) = '$srcIP' OR '$srcIP' = 'NULL') AND\n  (INET_NTOA(dstIP) = '$dstIP' OR '$dstIP' = 'NULL') AND\n  (srcPort = '$srcPort' OR '$srcPort' = 'NULL') AND\n  (dstPort = '$dstPort' OR '$dstPort' = 'NULL') AND\n  (protocol = '$protocol' OR '$protocol' = 'NULL') \nGROUP BY 1,2\nORDER BY $__timeGroup(data_time_date,1s)"
    }
   ]
  },
  {
   "title": "业务流统计结果",
   "type": "table",
   "description": "此界面展示了经过当前eNB的每个业务的平均比特率、平均包数以及流类型(iot、voip和vedio)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(INET_NTOA(srcIP),' : ',srcPort,'->',INET_NTOA(dstIP),' : ',dstPort) AS metric,\n  INET_NTOA(srcIP),\n  srcPort,\n  INET_NTOA(dstIP),\n  dstPort,\n  CONCAT(INET_NTOA(srcIP),' : ',srcPort),\n  CONCAT(INET_NTOA(dstIP),' : ',dstPort),\n  protocol,\n  averBytes,\n  averPkts,\n  flowType\nFROM measure"
    }
   ]
  }
 ]
}